name: Build

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ "develop" ]
    tags: [ "v**" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  sbt-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: sbt +test
  build-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build native app
        run: sbt "project leaderboard-bifunctor-tf; GraalVMNativeImage/packageBin"
      - name: Check native app
        run: ./distage-example-bifunctor-tf/target/graalvm-native-image/leaderboard-bifunctor-tf :help